// DELETE
const DELETE_ORDER = 'DELETE_ORDER';
const DELETE_USER = 'DELETE_USER'

// GET
const MATCH_DETAILS = 'MATCH_DETAILS';
const GET_MATCHS = 'GET_MATCHS';
const GET_USER_ACTIVITY = 'GET_USER_ACTIVITY'
const GET_USER_INFO = 'GET_USER_INFO'
const GET_USER_ORDERS = 'GET_USER_ORDERS'

// PATCH
const UPDATE_MATCH = 'UPDATE_MATCH';
const UPDATE_USER = 'UPDATE_USER';

// POST
const POST_BET = 'POST_BET'
const POST_ORDER = 'POST_ORDER'
const POST_PAYMENT = 'POST_PAYMENT'
const POST_USER = 'POST_USER'