const bet = [
  {
    status: 'Active',
    amount: 10,
    betTo: 'homeBet',
    multiplier: 1.8,
    userId: 1,
    orderId: 1,
    matchId: 135719,
  },
  {
    status: 'Active',
    amount: 15,
    betTo: 'homeBet',
    multiplier: 1.8,
    userId: 1,
    orderId: 1,
    matchId: 135722,
  },
  {
    status: 'Active',
    amount: 5,
    betTo: 'homeBet',
    multiplier: 1.8,
    userId: 2,
    orderId: 2,
    matchId: 135724,
  },
  {
    status: 'Active',
    amount: 10,
    betTo: 'homeBet',
    multiplier: 1.8,
    userId: 3,
    orderId: 3,
    matchId: 135725,
  },
  {
    status: 'Active',
    amount: 10,
    betTo: 'homeBet',
    multiplier: 1.8,
    userId: 3,
    orderId: 4,
    matchId: 135734,
  },
  {
    status: 'Active',
    amount: 10,
    betTo: 'awayBet',
    multiplier: 2.5,
    userId: 3,
    orderId: 4,
    matchId: 135745,
  },
  {
    status: 'Active',
    amount: 24,
    betTo: 'awayBet',
    multiplier: 2.5,
    userId: 4,
    orderId: 5,
    matchId: 135749,
  },
  {
    status: 'Active',
    amount: 5,
    betTo: 'awayBet',
    multiplier: 2.5,
    userId: 6,
    orderId: 7,
    matchId: 135750,
  },
  {
    status: 'Active',
    amount: 15,
    betTo: 'awayBet',
    multiplier: 2.5,
    userId: 7,
    orderId: 8,
    matchId: 135752,
  },
];

module.exports = bet